const currencies = [
  { label: 'Afghan afghani', value: 'afn' },
  { label: 'Albanian lek', value: 'all' },
  { label: 'Algerian dinar', value: 'dzd' },
  { label: 'Angolan kwanza', value: 'aoa' },
  { label: 'Argentine peso', value: 'ars' },
  { label: 'Armenian dram', value: 'amd' },
  { label: 'Aruban florin', value: 'awg' },
  { label: 'Australian dollar', value: 'aud' },
  { label: 'Azerbaijani manat', value: 'azn' },
  { label: 'Bahamian dollar', value: 'bsd' },
  { label: 'Bahraini dinar', value: 'bhd' },
  { label: 'Bangladeshi taka', value: 'bdt' },
  { label: 'Barbados dollar', value: 'bbd' },
  { label: 'Belarusian ruble', value: 'byn' },
  { label: 'Belize dollar', value: 'bzd' },
  { label: 'Bermudian dollar', value: 'bmd' },
  { label: 'Bhutanese ngultrum', value: 'btn' },
  { label: 'Boliviano', value: 'bob' },
  { label: 'Bosnia and Herzegovina convertible mark', value: 'bam' },
  { label: 'Botswana pula', value: 'bwp' },
  { label: 'Brazilian real', value: 'brl' },
  { label: 'Brunei dollar', value: 'bnd' },
  { label: 'Bulgarian lev', value: 'bgn' },
  { label: 'Burundian franc', value: 'bif' },
  { label: 'Cambodian riel', value: 'khr'},
  { label: 'Canadian dollar', value: 'cad'},
  { label: 'Cape Verdean escudo', value: 'cve'},
  { label: 'Cayman Islands dolla', value: 'kyd'},
  { label: 'CFA franc BCEAO', value: 'xof'},
  { label: 'CFA franc BEAC', value: 'xaf'},
  { label: 'CFP franc (franc Pacifique)', value: 'xpf'},
  { label: 'Chilean peso', value: 'clp'},
  { label: 'Colombian peso', value: 'cop'},
  { label: 'Comoro franc', value: 'kmf'},
  { label: 'Congolese franc', value: 'cdf'},
  { label: 'Costa Rican colon', value: 'crc'},
  { label: 'Croatian kuna', value: 'hrk'},
  { label: 'Cuban convertible peso', value: 'cuc'},
  { label: 'Cuban peso', value: 'cup'},
  { label: 'Czech koruna', value: 'czk'},
  { label: 'Danish krone', value: 'dkk'},
  { label: 'Djiboutian franc', value: 'djf'},
  { label: 'Dominican peso', value: 'dop'},
  { label: 'East Caribbean dollar', value: 'xcd'},
  { label: 'Egyptian pound', value: 'egp'},
  { label: 'Eritrean nakfa', value: 'ern'},
  { label: 'Ethiopian birr', value: 'etb'},
  { label: 'Euro', value: 'eur'},
  { label: 'Falkland Islands pound', value: 'fkp'},
  { label: 'Fiji dollar', value: 'fjd'},
  { label: 'Gambian dalasi', value: 'gmd'},
  { label: 'Georgian lari', value: 'gel'},
  { label: 'Ghanaian cedi', value: 'ghs'},
  { label: 'Gibraltar pound', value: 'gip'},
  { label: 'Guatemalan quetzal', value: 'gtq'},
  { label: 'Guinean franc', value: 'gnf'},
  { label: 'Guyanese dollar', value: 'gyd'},
  { label: 'Haitian gourde', value: 'htg'},
  { label: 'Honduran lempira', value: 'hnl'},
  { label: 'Hong Kong dollar', value: 'hkd'},
  { label: 'Hungarian forint', value: 'huf'},
  { label: 'Icelandic króna', value: 'isk'},
  { label: 'Indian rupee', value: 'inr'},
  { label: 'Indonesian rupiah', value: 'idr'},
  { label: 'Iranian rial', value: 'irr'},
  { label: 'Iraqi dinar', value: 'iqd'},
  { label: 'Israeli new shekel', value: 'ils'},
  { label: 'Jamaican dollar', value: 'jmd'},
  { label: 'Japanese yen', value: 'jpy'},
  { label: 'Jordanian dinar', value: 'jod'},
  { label: 'Kazakhstani tenge', value: 'kzt'},
  { label: 'Kenyan shilling', value: 'kes'},
  { label: 'Kuwaiti dinar', value: 'kwd'},
  { label: 'Kyrgyzstani som', value: 'kgs'},
  { label: 'Lao kip', value: 'lak'},
  { label: 'Lebanese pound', value: 'lbp'},
  { label: 'Lesotho lot', value: 'lsl'},
  { label: 'Liberian dollar', value: 'lrd'},
  { label: 'Libyan dinar', value: 'lyd'},
  { label: 'Macanese pataca', value: 'mop'},
  { label: 'Macedonian denar', value: 'mkd'},
  { label: 'Malagasy ariary', value: 'mga'},
  { label: 'Malawian kwacha', value: 'mwk'},
  { label: 'Malaysian ringgit', value: 'myr'},
  { label: 'Maldivian rufiyaa', value: 'mvr'},
  { label: 'Mauritian rupee', value: 'mur'},
  { label: 'Mexican peso', value: 'mxn'},
  { label: 'Moldovan leu', value: 'mdl'},
  { label: 'Mongolian tögrög', value: 'mnt'},
  { label: 'Moroccan dirham', value: 'mad'},
  { label: 'Mozambican metical', value: 'mzn'},
  { label: 'Myanmar kyat', value: 'mmk'},
  { label: 'Namibian dollar', value: 'nad'},
  { label: 'Nepalese rupee', value: 'npr'},
  { label: 'Netherlands Antillean guilder', value: 'ang'},
  { label: 'New Taiwan dollar', value: 'twd'},
  { label: 'New Zealand dollar', value: 'nzd'},
  { label: 'Nicaraguan córdoba', value: 'nio'},
  { label: 'Nigerian naira', value: 'ngn'},
  { label: 'North Korean won', value: 'kpw'},
  { label: 'Norwegian krone', value: 'nok'},
  { label: 'Omani rial', value: 'omr'},
  { label: 'Pakistani rupee', value: 'pkr'},
  { label: 'Panamanian balboa', value: 'pab'},
  { label: 'Papua New Guinean kina', value: 'pgk'},
  { label: 'Paraguayan guaraní', value: 'pyg'},
  { label: 'Peruvian sol', value: 'pen'},
  { label: 'Philippine peso', value: 'php'},
  { label: 'Polish złoty', value: 'pln'},
  { label: 'Pound sterling', value: 'gbp'},
  { label: 'Qatari riyal', value: 'qar'},
  { label: 'Renminbi (Chinese) yuan', value: 'cny'},
  { label: 'Romanian leu', value: 'ron'},
  { label: 'Russian ruble', value: 'rub'},
  { label: 'Rwandan franc', value: 'rwf'},
  { label: 'Saint Helena pound', value: 'shp'},
  { label: 'Samoan tala', value: 'wst'},
  { label: 'Saudi riyal', value: 'sar'},
  { label: 'Serbian dinar', value: 'rsd'},
  { label: 'Seychelles rupee', value: 'scr'},
  { label: 'Sierra Leonean leone', value: 'sll'},
  { label: 'Singapore dollar', value: 'sgd'},
  { label: 'Solomon Islands dollar', value: 'sbd'},
  { label: 'Somali shilling', value: 'sos'},
  { label: 'South African rand', value: 'zar'},
  { label: 'South Korean won', value: 'krw'},
  { label: 'South Sudanese pound', value: 'ssp'},
  { label: 'Sri Lankan rupee', value: 'lkr'},
  { label: 'Sudanese pound', value: 'sdg'},
  { label: 'Surinamese dollar', value: 'srd'},
  { label: 'Swazi lilangeni', value: 'szl'},
  { label: 'Swedish krona', value: 'sek'},
  { label: 'Swiss franc', value: 'chf'},
  { label: 'Syrian pound', value: 'syp'},
  { label: 'Tajikistani somoni', value: 'tjs'},
  { label: 'Tanzanian shilling', value: 'tzs'},
  { label: 'Thai baht', value: 'thb'},
  { label: 'Tongan paʻanga', value: 'top'},
  { label: 'Trinidad and Tobago dollar', value: 'ttd'},
  { label: 'Tunisian dinar', value: 'tnd'},
  { label: 'Turkish lira', value: 'try'},
  { label: 'Turkmenistan manat', value: 'tmt'},
  { label: 'Ugandan shilling', value: 'ugx'},
  { label: 'Ukrainian hryvnia', value: 'uah'},
  { label: 'United Arab Emirates dirham', value: 'aed'},
  { label: 'United States dollar', value: 'usd'},
  { label: 'Uruguayan peso', value: 'uyu'},
  { label: 'Uzbekistan som', value: 'uzs'},
  { label: 'Vanuatu vatu', value: 'vuv'},
  { label: 'Vietnamese đồng', value: 'vnd'},
  { label: 'Yemeni rial', value: 'yer'},
  { label: 'Zambian kwacha', value: 'zmw'}
  ]

  export default currencies