const languages = [
    { value: "af", label: "Afrikaans" },
    { value: "sq", label: "Albanian" },
    { value: "am", label: "Amharic" },
    { value: "ar", label: "Arabic" },
    { value: "hy", label: "Armenian" },
    { value: "ay", label: "Aymara" },
    { value: "az", label: "Azerbaijani" },
    { value: "be", label: "Belarusian" },
    { value: "bn", label: "Bengali; Bangla" },
    { value: "bi", label: "Bislama" },
    { value: "bs", label: "Bosnian" },
    { value: "bg", label: "Bulgarian" },
    { value: "my", label: "Burmese" },
    { value: "ca", label: "Catalan; Valencian" },
    { value: "ch", label: "Chamorro" },
    { value: "ny", label: "Chichewa; Chewa; Nyanja" },
    { value: "zh", label: "Chinese" },
    { value: "hr", label: "Croatian" },
    { value: "cs", label: "Czech" },
    { value: "da", label: "Danish" },
    { value: "dv", label: "Divehi" },
    { value: "nl", label: "Dutch" },
    { value: "dz", label: "Dzongkha" },
    { value: "en", label: "English" },
    { value: "et", label: "Estonian" },
    { value: "fo", label: "Faroese" },
    { value: "fj", label: "Fijian" },
    { value: "fi", label: "Finnish" },
    { value: "fr", label: "French" },
    { value: "ff", label: "Fula" },
    { value: "ka", label: "Georgian" },
    { value: "de", label: "German" },
    { value: "el", label: "Greek" },
    { value: "gn", label: "GuaranÃ­" },
    { value: "ht", label: "Haitian" },
    { value: "he", label: "Hebrew" },
    { value: "hi", label: "Hindi" },
    { value: "hu", label: "Hungarian" },
    { value: "is", label: "Icelandic" },
    { value: "id", label: "Indonesian" },
    { value: "ga", label: "Irish" },
    { value: "it", label: "Italian" },
    { value: "ja", label: "Japanese" },
    { value: "kl", label: "Kalaallisut, Greenlandic" },
    { value: "kk", label: "Kazakh" },
    { value: "km", label: "Khmer" },
    { value: "rw", label: "Kinyarwanda" },
    { value: "rn", label: "Kirundi" },
    { value: "kg", label: "Kongo" },
    { value: "ko", label: "Korean" },
    { value: "ku", label: "Kurdish" },
    { value: "ky", label: "Kyrgyz" },
    { value: "lo", label: "Lao" },
    { value: "la", label: "Latin" },
    { value: "lv", label: "Latvian" },
    { value: "ln", label: "Lingala" },
    { value: "lt", label: "Lithuanian" },
    { value: "lu", label: "Luba-Katanga" },
    { value: "lb", label: "Luxembourgish" },
    { value: "mk", label: "Macedonian" },
    { value: "mg", label: "Malagasy" },
    { value: "ms", label: "Malay" },
    { value: "mt", label: "Maltese" },
    { value: "gv", label: "Manx" },
    { value: "mi", label: "MÄori" },
    { value: "mh", label: "Marshallese" },
    { value: "mn", label: "Mongolian" },
    { value: "na", label: "Nauru" },
    { value: "ne", label: "Nepali" },
    { value: "no", label: "Norwegian" },
    { value: "nb", label: "Norwegian BokmÃ¥l" },
    { value: "nd", label: "North Ndebele" },
    { value: "nn", label: "Norwegian Nynorsk" },
    { value: "ps", label: "Pashto" },
    { value: "fa", label: "Persian (Farsi)" },
    { value: "pl", label: "Polish" },
    { value: "pt", label: "Portuguese" },
    { value: "pa", label: "Punjabi" },
    { value: "qu", label: "Quechua" },
    { value: "ro", label: "Romanian" },
    { value: "ru", label: "Russian" },
    { value: "sm", label: "Samoan" },
    { value: "sg", label: "Sango" },
    { value: "sr", label: "Serbian" },
    { value: "sn", label: "Shona" },
    { value: "si", label: "Sinhalese" },
    { value: "sk", label: "Slovak" },
    { value: "sl", label: "Slovene" },
    { value: "so", label: "Somali" },
    { value: "nr", label: "South Ndebele" },
    { value: "st", label: "Southern Sotho" },
    { value: "az", label: "South Azerbaijani" },
    { value: "es", label: "Spanish" },
    { value: "sw", label: "Swahili" },
    { value: "ss", label: "Swati" },
    { value: "sv", label: "Swedish" },
    { value: "tg", label: "Tajik" },
    { value: "ta", label: "Tamil" },
    { value: "th", label: "Thai" },
    { value: "ti", label: "Tigrinya" },
    { value: "to", label: "Tonga (Tonga Islands)" },
    { value: "ts", label: "Tsonga" },
    { value: "tn", label: "Tswana" },
    { value: "tr", label: "Turkish" },
    { value: "tk", label: "Turkmen" },
    { value: "uk", label: "Ukrainian" },
    { value: "ur", label: "Urdu" },
    { value: "uz", label: "Uzbek" },
    { value: "ve", label: "Venda" },
    { value: "vi", label: "Vietnamese" },
    { value: "xh", label: "Xhosa" },
    { value: "zu", label: "Zulu" }
  ]

export default languages